---
- name: Cau hinh tren Router1
  hosts: R1
  gather_facts: no

  tasks:
    - name: Dat IP cho cac cong
      ios_l3_interface:
        name: Ethernet0/{{ item.name }}
        ipv4: 192.168.{{ item.number }}.1/24
      with_items:
        - { name: "1", number: 1}
        - { name: "2", number: 12}
    - name: no shut cac cong
      ios_config:
        parents:
          - int Ethernet0/{{item.name}}
        lines:
          - no shut
      with_items:
        - { name: "1"}
        - { name: "2"}
    
- name: Cau hinh tren Router1
  hosts: R2
  gather_facts: no

  tasks:
    - name: Dat IP cho cac cong
      ios_l3_interface:
        name: Ethernet0/{{ item.name }}
        ipv4: 192.168.{{ item.number }}.{{ item.number1 }}/24
      with_items:
        - { name: "1", number: 2, number1: 1}
        - { name: "2", number: 12, number1: 2}
    - name: no shut cac cong
      ios_config:
        parents:
          - int Ethernet0/{{item.name}}
        lines:
          - no shut
      with_items:
        - { name: "1"}
        - { name: "2"}

- name: Cau hinh tren Router1
  hosts: all
  gather_facts: no
  tasks:

    - name: static route 
      ios_config:
        parents:
          - int e0/{{ item.name }}
        lines:
          - ip route 192.168.{{ item.number }}.0 255.255.255.0 192.168.{{ item.number1 }}.{{ item.number2 }}
      with_items:
         - { name: "1", number: 1, number1: 12}
         - { name: "1", number: 2, number1: 12, number2: 2}
