---
- name: tao vlan
  hosts: all
  gather_facts: no

  tasks:
    - name: Show vlan
      ios_command:
        commands:
          - show vlan
      register: show_vlan

    - debug: var=show_vlan.stdout_lines
